name: testing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.4
  animated_bottom_navigation_bar: ^0.3.3
  iconly: ^1.0.1
  google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true




  assets:
    - assets/